### ISSUE TITLE
Adding supabase-kt

### ISSUE THREAD

**Issue by jan-tennert** [supabase-community/.github#17]
Hey I made a library for **Kotlin (JS, JVM, Android)** which provides APIs for **Auth (GoTrue)**, **Realtime**, **Storage**, **Edge Functions, Postgrest**
and I wanted to ask if this is the right place to share it, I wasn't sure if I should do a pr directly, so I wanted to ask here.

Project: https://github.com/jan-tennert/SupaCompose

**Comment by jan-tennert** [comment]
@thorwebdev

**Comment by thorwebdev** [comment]
Hey @jan-tennert that's great, thanks for sharing. Would you be up for splitting this out into different repos (gotrue-kt, functions-kt, realtime-kt, storage-kt) and then compose them together in a `supabase-kt` and transfer these repos here?

That would be our preferred project structure. If that sounds like too much work, no worries, then I'll have a think about how to showcase your project as is.

**Comment by jan-tennert** [comment]
I mean I can move and rename the modules as there are already seperated. But they are using the same build system for publishing so they always have the same version so I'm not sure how I might split these into multiple repos. Also I tried to not just like copy the other sdks, I made them as Kotlin idiomatic as possible. On top of that things like the Realtime module and the Auth (GoTrue) module are strictly seperated so if you want to like listen to postgrest changes with auth  you need the Auth module. Also whats with the other postgrest-kt client?

**Comment by jan-tennert** [comment]
So the main problem is probably how I'm gonna split those modules into repos as they share the same build system

**Comment by jan-tennert** [comment]
@thorwebdev

**Comment by jan-tennert** [comment]
@thorwebdev

**Comment by jan-tennert** [comment]
Or you could leave the modules as it and provide a README for each module and add a link to them to the README

**Comment by jan-tennert** [comment]
So in the end it would look like this:
Supabase-kt: supabase-kt
Postgrest-kt: supabase-kt/tree/master/Postgrest
...

**Comment by jan-tennert** [comment]
Also should I publish to the new dependencies to the **io.supabase** group on maven central? If yes I also probably also need the authorization things for that

**Comment by jan-tennert** [comment]
@thorwebdev any updates on this?

**Comment by jan-tennert** [comment]
So I would still have all modules in one repo, rename them, transfer them, and publish them to maven central as io.supabase (if I have the authorization). And link the links on the README to the corresponding READMEs in the repo. Is that correct?

**Comment by jan-tennert** [comment]
Ok for now I wont publish it to another group id as it's probably easier for me

**Comment by jan-tennert** [comment]
Can't transfer https://github.com/jan-tennert/supabase-kt to supabase-community. No permission
